image: python:3.9.0

cache:
  key: dependencies
  paths:
    - .cache/pip/
    - .venv

before_script:
  - python --version
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  - poetry config experimental.new-installer false
  - poetry install -vv

test:
  script:
    - poetry run py.test -vvxra --tb=short --cov=expense_management --cov-report=term-missing tests
